### ISSUE TITLE
importing multiValue-Properties with empty Array will lead to wrong JcrType

### ISSUE THREAD

**Issue by mbrahm** [bloomreach-forge/content-export-import#22]
Hi,

the problem is more in the Pojo-Binding but I cannot create an issue in that repo.

when you have a properties definition like this in the JSON
`
"properties" : [ {
          "name" : "name",
          "type" : "STRING",
          "multiple" : true,
          "values" : [ ]
        }
`

and you import this with  the exim plugin, the property is created with type DOUBLE. The reason is that DefaultJcrContentNodeBinder is not setting any type in the JcrProperty and one is guessed.  

DefaultJcrContentNodeBinder.createJcrValuesFromContentProperty (around line 306)

`for (String stringValue : contentProp.getValues()) {
                jcrValue = valueConverter.toJcrValue(contentProp.getType().toString(), stringValue);

                if (jcrValue != null) {
                    jcrValues.add(jcrValue);
                }
            }`

The type is only known, when you we have at least one value and when the property is later set at the jcrNode the property is created as a DOUBLE (around line 195)
`
 if (contentProp.isMultiple()) {
                        try {
                            jcrDataNode.setProperty(propName, jcrValues); <- here the resulting type is DOUBLE in case jcrValues is an empty list
                        } catch (ArrayIndexOutOfBoundsException ignore) {
                            // Due to REPO-1428, let's ignore this kind of exception for now...
                        }
                    } 
`

For now we found a workaround by copy/pasting some of the code and setting the propertyTpe explicitly based on the ContentPropertyType. But it would be nice if you can fix this somehow.

Kind regards

Matthias

**Comment by maxgda** [comment]
Hi Matthias, 

Thanks for the detailed report. I’ve just opened the Issues section for the Pojo-Binding repository, so you can now create an issue or, if possible, open a merge request with a proposed fix or workaround. Feel free to tag me there if you have any questions.
